/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssociationContextObject : Field association for example PROJECT\\_ID.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AssociationContextObject {
    #[serde(rename="ProjectIdAssociationContext")]
    ProjectIdAssociationContext {
        #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
        identifier: Option<serde_json::Value>,
    },
}

impl Default for AssociationContextObject {
    fn default() -> Self {
        Self::ProjectIdAssociationContext {
            identifier: Default::default(),
        }
        
    }
}


