/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentArchiveImpl {
    /// The list of the items included in the archive.
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::AttachmentArchiveEntry>>,
    /// The number of items in the archive.
    #[serde(rename = "totalEntryCount", skip_serializing_if = "Option::is_none")]
    pub total_entry_count: Option<i32>,
}

impl AttachmentArchiveImpl {
    pub fn new() -> AttachmentArchiveImpl {
        AttachmentArchiveImpl {
            entries: None,
            total_entry_count: None,
        }
    }
}

