/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CustomContextVariable {
    #[serde(rename="user")]
    User(Box<models::UserContextVariable>),
    #[serde(rename="issue")]
    Issue(Box<models::IssueContextVariable>),
    #[serde(rename="json")]
    Json(Box<models::JsonContextVariable>),
}

impl Default for CustomContextVariable {
    fn default() -> Self {
        Self::User(Default::default())
    }
}


