/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JqlFunctionPrecomputationUpdateRequestBean : List of pairs (id and value) for precomputation updates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JqlFunctionPrecomputationUpdateRequestBean {
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::JqlFunctionPrecomputationUpdateBean>>,
}

impl JqlFunctionPrecomputationUpdateRequestBean {
    /// List of pairs (id and value) for precomputation updates.
    pub fn new() -> JqlFunctionPrecomputationUpdateRequestBean {
        JqlFunctionPrecomputationUpdateRequestBean {
            values: None,
        }
    }
}

