/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationSchemeEventIdPayload : The event ID to use for reference in the payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSchemeEventIdPayload {
    /// The event ID to use for reference in the payload
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl NotificationSchemeEventIdPayload {
    /// The event ID to use for reference in the payload
    pub fn new() -> NotificationSchemeEventIdPayload {
        NotificationSchemeEventIdPayload {
            id: None,
        }
    }
}

