/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-ccbf72d894d6b699175624f7a94244e68c9dbc6d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusWorkflowUsageDto : Workflows using the status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusWorkflowUsageDto {
    /// The status ID.
    #[serde(rename = "statusId", skip_serializing_if = "Option::is_none")]
    pub status_id: Option<String>,
    #[serde(rename = "workflows", skip_serializing_if = "Option::is_none")]
    pub workflows: Option<Box<models::StatusWorkflowUsagePage>>,
}

impl StatusWorkflowUsageDto {
    /// Workflows using the status.
    pub fn new() -> StatusWorkflowUsageDto {
        StatusWorkflowUsageDto {
            status_id: None,
            workflows: None,
        }
    }
}

